openapi: 3.0.0
info:
  title: Interactive Forest VR — Backend API (Photon Server Mode)
  version: 2.0.0
  description: >
    Backend per architettura Photon Fusion Server Mode (on-premise).  
    In questa modalità il backend comunica direttamente con il server Photon locale,
    legge lo stato delle room e gestisce autonomamente i salvataggi.  
    JWT per utenti, HMAC SHA-256 per webhook Photon, TLS 1.3 obbligatorio.

servers:
  - url: https://edge.local/api/v1

tags:
  - name: Auth
  - name: Sessions
  - name: Participants
  - name: Saves
  - name: Webhooks
  - name: Ops

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    hmacAuth:
      type: apiKey
      in: header
      name: X-Signature

  parameters:
    CorrelationId:
      name: X-Correlation-Id
      in: header
      required: true
      description: Identificatore della stanza (uguale a room_id)
      schema: { type: string }

  schemas:
    Problem:
      type: object
      required: [title]
      properties:
        type: { type: string }
        title: { type: string }
        detail: { type: string }
        instance: { type: string }
        correlation_id: { type: string }
        timestamp: { type: string, format: date-time }

    TokenResponse:
      type: object
      properties:
        access_token: { type: string }
        refresh_token: { type: string }
        token_type: { type: string, example: bearer }

    SessionItem:
      type: object
      properties:
        room_id: { type: string }
        state: { type: string, enum: [active, closed, interrupted] }
        updated_at: { type: string, format: date-time }

    Participant:
      type: object
      properties:
        user_id: { type: string }
        actor_number: { type: integer }
        joined_at: { type: string, format: date-time }

    SaveIndex:
      type: object
      properties:
        room_id: { type: string }
        manual:
          type: array
          items:
            type: object
            properties:
              slot: { type: integer, minimum: 1, maximum: 3 }
              occupied: { type: boolean }
              save_id: { type: string, nullable: true }
              snapshot_version: { type: integer, nullable: true }
              updated_at: { type: string, format: date-time, nullable: true }
        auto:
          type: object
          properties:
            occupied: { type: boolean }
            save_id: { type: string, nullable: true }
            snapshot_version: { type: integer, nullable: true }
            updated_at: { type: string, format: date-time, nullable: true }

    SnapshotV1:
      type: object
      additionalProperties: false
      properties:
        room_id: { type: string }
        timestamp: { type: string, format: date-time }
        users: { type: array, items: { type: string } }
        terrain:
          type: object
          properties:
            source: { type: string }
            bbox:
              type: array
              items: { type: number }
              minItems: 4
              maxItems: 4
        metadata:
          type: object
          properties:
            landslides:
              type: array
              items:
                type: object
                properties:
                  id: { type: string }
                  lat: { type: number }
                  lon: { type: number }
                  risk: { type: string, enum: [low, medium, high] }
        session_state:
          type: object
          properties:
            camera: { type: string }
            zoom: { type: number }
            anchor_points: { type: array, items: { type: object } }
        version: { type: integer }

security:
  - bearerAuth: []

paths:

  /auth/login:
    post:
      tags: [Auth]
      summary: Login utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } }
        '401':
          description: Credenziali non valide
          content:
            application/problem+json: { schema: { $ref: '#/components/schemas/Problem' } }

  /auth/refresh:
    post:
      tags: [Auth]
      summary: Refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refresh_token]
              properties:
                refresh_token: { type: string }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } } } }
        '401': { description: Token non valido, content: { application/problem+json: { schema: { $ref: '#/components/schemas/Problem' } } } }

  /sessions:
    post:
      tags: [Sessions]
      summary: Registra una nuova sessione Photon (Server Mode)
      responses:
        '201':
          description: Sessione creata
          content:
            application/json:
              schema:
                type: object
                properties:
                  room_id: { type: string }
                  join_code: { type: string }
        '401': { description: Non autorizzato }
    get:
      tags: [Sessions]
      summary: Elenca le sessioni attive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/SessionItem' }

  /sessions/{room_id}/participants:
    get:
      tags: [Participants]
      summary: Elenca i partecipanti correnti di una stanza
      parameters:
        - name: room_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Participant' }
        '404': { description: Room non trovata }

  /session/{room_id}/saves:
    get:
      tags: [Saves]
      summary: Ritorna l'indice dei salvataggi (3 manuali + 1 auto)
      parameters:
        - name: room_id
          in: path
          required: true
          schema: { type: string }
        - $ref: '#/components/parameters/CorrelationId'
      responses:
        '200':
          description: OK
          content:
            application/json: { schema: { $ref: '#/components/schemas/SaveIndex' } }
        '403': { description: Non autorizzato }
        '404': { description: Room non trovata }

  /session/{room_id}/save:
    post:
      tags: [Saves]
      summary: Esegue salvataggio lato server (Server Mode)
      description: >
        In Server Mode il client non invia i dati della sessione.  
        Il backend interroga direttamente lo stato della room su Photon Server
        e registra lo snapshot corrente nel database.
      parameters:
        - name: room_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '201': { description: Snapshot salvato dal server }
        '404': { description: Room non trovata o inattiva }
        '500': { description: Errore durante la lettura dello stato dalla room }

  /webhooks/photon/game-created:
    post:
      tags: [Webhooks]
      summary: Creazione stanza Server Mode
      security: [ { hmacAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [room_id, event_id, timestamp]
              properties:
                room_id: { type: string }
                event_id: { type: string }
                timestamp: { type: string, format: date-time }
      responses:
        '204': { description: OK }
        '401': { description: Firma non valida }

  /webhooks/photon/player-joined:
    post:
      tags: [Webhooks]
      summary: Utente entrato nella stanza
      security: [ { hmacAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [room_id, player_id, actor_number, event_id, timestamp]
              properties:
                room_id: { type: string }
                player_id: { type: string }
                actor_number: { type: integer }
                event_id: { type: string }
                timestamp: { type: string, format: date-time }
      responses:
        '204': { description: OK }

  /webhooks/photon/player-left:
    post:
      tags: [Webhooks]
      summary: Utente uscito dalla stanza
      security: [ { hmacAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [room_id, player_id, actor_number, event_id, timestamp]
              properties:
                room_id: { type: string }
                player_id: { type: string }
                actor_number: { type: integer }
                event_id: { type: string }
                timestamp: { type: string, format: date-time }
      responses:
        '204': { description: OK }

  /webhooks/photon/game-closed:
    post:
      tags: [Webhooks]
      summary: Chiusura stanza (Server Mode)
      description: >
        Evento inviato da Photon Server quando la stanza viene chiusa.  
        In questa modalità il backend, ricevendo il webhook, legge lo stato corrente
        della room direttamente dal server Photon e registra automaticamente
        un salvataggio nello slot dedicato all’autosave, senza intervento dei client.
      security: [ { hmacAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [room_id, event_id, timestamp]
              properties:
                room_id: { type: string }
                event_id: { type: string }
                timestamp: { type: string, format: date-time }
      responses:
        '204': { description: OK }
        '500': { description: Errore nel salvataggio automatico }

  /health:
    get:
      tags: [Ops]
      summary: Stato applicativo
      responses:
        '200': { description: OK }

  /ready:
    get:
      tags: [Ops]
      summary: Verifica connessione DB e segreti
      responses:
        '200': { description: Ready }
        '500': { description: Not Ready }

  /metrics:
    get:
      tags: [Ops]
      summary: Metriche Prometheus
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: { type: string }
